version: "2.23.0"

services:
    app:
        build: .
        ports:
            - 8000:8000
        volumes:
            - .:/var/www/html
            - ./vendor/:/var/www/html/vendor
        depends_on:
            - database

    database:
        image: mysql:8.2.0
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - mysql-data:/var/lib/mysql

    PhpMyAdmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        depends_on:
            - database
        ports:
          - 8001:80

volumes:
  mysql-data: ~
